# Microservice Expedition - profil dev (local, une seule machine)

eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.hostname=microservice-expedition
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*
